// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRBiw5og42xAf6wXX5sZV05cleJSF2JA',
    appId: '1:133958366051:web:b8e64805413d646b971956',
    messagingSenderId: '133958366051',
    projectId: 'doukhaber',
    authDomain: 'doukhaber.firebaseapp.com',
    storageBucket: 'doukhaber.appspot.com',
    measurementId: 'G-1S1JEDYR4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgegil-VO49UvHhHCJDfgbvhL596Lqghk',
    appId: '1:133958366051:android:b3a198f6581230a5971956',
    messagingSenderId: '133958366051',
    projectId: 'doukhaber',
    storageBucket: 'doukhaber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhj-orAlscCR1TCYxKFbE6yr8-F4UdoM',
    appId: '1:133958366051:ios:e48641e5d819d6ac971956',
    messagingSenderId: '133958366051',
    projectId: 'doukhaber',
    storageBucket: 'doukhaber.appspot.com',
    iosClientId: '133958366051-vclu0krdhhv9jub9jraeh9uhch3b2mpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinepopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWhj-orAlscCR1TCYxKFbE6yr8-F4UdoM',
    appId: '1:133958366051:ios:2311f977e09b54b0971956',
    messagingSenderId: '133958366051',
    projectId: 'doukhaber',
    storageBucket: 'doukhaber.appspot.com',
    iosClientId: '133958366051-rsnkm47kkr48bjp0ednn7etkmfvn6st5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinepopapp.RunnerTests',
  );
}
